SofaDefrost/SoftRobots

component/controller/SerialPortBridgeGeneric.cpp, component/controller/SerialPortBridgeGeneric.h
This PR includes:
1- removed a convertion of the datas from meter to millimeter that was hidden from users, and only done in the particular case of precise=true. 
2- added a warning about that
3- more detailed informations about the datas
4- minor cleaning such as removed some untruth comments.
This PR lacks:
1- changes in simulation and arduino code of existing prototypes that will be impacted by these changes...
I would really like the opinions and advices of @MarioSanz  on this PR. And maybe a list of simulations and arduino codes that should be updated.
=> [controller] added more info about the datas and cleaned the code

component/behavior/SoftRobotsConstraint.cpp, component/behavior/SoftRobotsConstraint.h, component/constraint/CableConstraint.cpp, component/constraint/CableConstraint.h, component/constraint/PartialRigidificationConstraint.cpp, component/constraint/PartialRigidificationConstraint.h, component/constraint/SurfacePressureConstraint.cpp, component/constraint/SurfacePressureConstraint.h, component/constraint/UnilateralPlaneConstraint.cpp, component/constraint/UnilateralPlaneConstraint.h, component/constraint/model/CableModel.cpp, component/constraint/model/CableModel.h, component/constraint/model/SurfacePressureModel.cpp, component/constraint/model/SurfacePressureModel.h, component/controller/AnimationEditor.cpp, component/controller/AnimationEditor.h, component/controller/CommunicationController.cpp, component/controller/DataVariationLimiter.cpp, component/controller/DataVariationLimiter.h, component/engine/CenterOfMass.cpp, component/engine/CenterOfMass.h, component/engine/VolumeFromTetrahedrons.cpp, component/engine/VolumeFromTetrahedrons.h, component/engine/VolumeFromTriangles.cpp, component/engine/VolumeFromTriangles.h, component/forcefield/PREquivalentStiffnessForceField.cpp, component/forcefield/PartialRigidificationForceField.cpp, component/forcefield/PipeForceField.cpp
=> [SoftRobots] Remove the SOFA_FLOAT (WIP didn't check it compiled)

docs/tutorials/Tripod/details/actuatedarm.py
In STLIB the name of the actuated was changed from BoxROI to BoxRoi.
=> [SoftRobots] FIX actuatedarm.py that was broken because of change in STLIB

CMakeLists.txt, cmake/environment.cmake, src/SoftRobots/component/initSoftRobots.cpp
A few changes done during my latest visit to Defrost team :wink:
=> Improve packaging

tests/CMakeLists.txt
Minor PR fixing the test of SoftRobot due to recent collection changes.
=> Fix CMake in test

CMakeLists.txt, src/SoftRobots/component/behavior/SoftRobotsBaseConstraint.h, src/SoftRobots/component/behavior/SoftRobotsConstraint.h, src/SoftRobots/component/constraint/SurfacePressureConstraint.h, src/SoftRobots/component/constraint/UnilateralPlaneConstraint.h, src/SoftRobots/component/controller/AnimationEditor.h, src/SoftRobots/component/controller/CommunicationController.h, src/SoftRobots/component/controller/DataVariationLimiter.h, src/SoftRobots/component/controller/SerialPortBridgeGeneric.h, src/SoftRobots/component/engine/CenterOfMass.h, src/SoftRobots/component/engine/VolumeFromTetrahedrons.h, src/SoftRobots/component/engine/VolumeFromTriangles.h, src/SoftRobots/component/initSoftRobots.cpp, src/SoftRobots/component/initSoftRobots.h.in
Fix compilation further to PR 1397 in SOFA master.
=> Fix compilation further to #1397

docs/examples/component/constraint/SurfacePressureConstraint/PressureVsVolumeGrowthControl.pyscn, src/SoftRobots/component/constraint/CableConstraint.h, src/SoftRobots/component/constraint/CableConstraint.inl, src/SoftRobots/component/constraint/SurfacePressureConstraint.h, src/SoftRobots/component/constraint/SurfacePressureConstraint.inl, src/SoftRobots/component/constraint/UnilateralPlaneConstraint.h, src/SoftRobots/component/constraint/UnilateralPlaneConstraint.inl, src/SoftRobots/component/constraint/model/CableModel.h, src/SoftRobots/component/constraint/model/CableModel.inl, src/SoftRobots/component/constraint/model/SurfacePressureModel.h, src/SoftRobots/component/constraint/model/SurfacePressureModel.inl, src/SoftRobots/component/controller/AnimationEditor.inl, src/SoftRobots/component/controller/CommunicationController.inl, src/SoftRobots/component/controller/SerialPortBridgeGeneric.cpp, src/SoftRobots/component/engine/CenterOfMass.inl, src/SoftRobots/component/engine/VolumeFromTetrahedrons.inl, src/SoftRobots/component/engine/VolumeFromTriangles.inl, src/SoftRobots/component/forcefield/PREquivalentStiffnessForceField.h, src/SoftRobots/component/forcefield/PREquivalentStiffnessForceField.inl, tests/component/constraint/SurfacePressureConstraintTest.cpp, tests/component/controller/SerialPortBridgeGenericTest.cpp
Everything is in the title. Fix might already have been done internally..
=> Fix due to change into d_componentState

CMakeLists.txt
Not really sure... but to match SOFA PR https://github.com/sofa-framework/sofa/pull/1357
=> CMake configuration is still looking for Metis which is now inside SofaSparseSolver

CMakeLists.txt, README.md, src/SoftRobots/component/camera/PointCloudProcessing.cpp, src/SoftRobots/component/camera/PointCloudProcessing.h, src/SoftRobots/component/camera/PointCloudStreaming.cpp, src/SoftRobots/component/camera/PointCloudStreaming.h
Hello,
I've taken the code from Zhongkai's gitlab repository and added it to the SoftRobots plugin. Basically, this adds a new component that retrieves & processes point clouds coming from a RealSense camera. I didn't look into the details but it seems to be standard segmenting, smoothing, clustering, outlier removal etc for 3D point clouds.
It's deactivated by default, and can be enabled through cmake by setting the SOFTROBOTS_WITH_CAMERA option to ON in cmake. Some small installation documentation is also added in the readme.md, explaining how to install the 2 dependencies for the plugin:
- the PCL library
- The kernel module for realsense & its associated SDK.
I don't know if master should be the target branch to merge this PR. if you prefer to have this on a separate branch I can …
=> ADD: Zhongkai's code

docs/examples/component/constraint/CableConstraint/sofapython3/Finger.py3
Hello, 
Thanks for your work with SofaPython3, it's great!  
I have a question @damienmarchal, the controller in this scene does not work.
`cable.addObject(FingerController(node=cable))`
I couldn't find any info on how to use the new Controller with SofaPython3 in the doc.
Could you help me with that? Thanks!
=> [docs] fix Finger.py3 

src/SoftRobots/component/constraint/SurfacePressureConstraint.inl
=> [constraint] Fix compilation in SurfacePressureConstraint.inl

src/SoftRobots/component/constraint/UnilateralPlaneConstraint.inl, src/SoftRobots/component/controller/AnimationEditor.inl, src/SoftRobots/component/controller/SerialPortBridgeGeneric.cpp, src/SoftRobots/component/engine/VolumeFromTetrahedrons.inl, src/SoftRobots/component/engine/VolumeFromTriangles.inl, src/SoftRobots/component/forcefield/PREquivalentStiffnessForceField.inl, tests/component/controller/AnimationEditorTest.cpp, tests/component/controller/SerialPortBridgeGenericTest.cpp
Now Data == or Data != is not anymore possible (no automatic access to the Data value)
This PR applies getValue and setValue where needed
=> Fix compilation: no more automatic getValue on data

tests/component/constraint/SurfacePressureConstraintTest.cpp, tests/component/constraint/UnilateralPlaneConstraintTest.cpp, tests/component/controller/AnimationEditorTest.cpp, tests/component/controller/DataVariationLimiterTest.cpp, tests/component/controller/SerialPortBridgeGenericTest.cpp, tests/component/engine/VolumeFromTetrahedronsTest.cpp, tests/component/engine/VolumeFromTrianglesTest.cpp
=> Fix compilation with ::testing::Types

CMakeLists.txt, SoftRobotsConfig.cmake.in, src/SoftRobots/component/initSoftRobots.cpp, src/SoftRobots/component/initSoftRobots.h.in
Changes done for SOFA v20.12 release.
- improve out-of-tree usage
- fix python scripts installation (py2 vs py3)
=> v20.12 changes

docs/examples/component/constraint/UnilateralPlaneConstraint/ArticulatedTentacle.pyscn, docs/examples/component/constraint/UnilateralPlaneConstraint/sofapython3/ArticulatedTentacle.py3scn, docs/examples/component/controller/CommunicationController/SimulationInverse_Sender.pyscn, docs/tutorials/CircularRobot/circularrobot.py, docs/tutorials/CircularRobot/circularrobot.py3, docs/tutorials/PneunetGripper/details/step7-grabTheCube.pyscn, tests/component/constraint/scenes/SurfacePressureConstraint.scn
BruteForceDetection is deprecated
=> Replace BruteForceDetection by BruteForceNarrowPhase+BVHNarrowPhase

src/SoftRobots/component/behavior/SoftRobotsConstraint.h, src/SoftRobots/component/constraint/CableConstraint.h, src/SoftRobots/component/constraint/PartialRigidificationConstraint.h, src/SoftRobots/component/constraint/SurfacePressureConstraint.h, src/SoftRobots/component/constraint/UnilateralPlaneConstraint.h, src/SoftRobots/component/constraint/model/AffineFunctionModel.h, src/SoftRobots/component/constraint/model/AffineFunctionModel.inl, src/SoftRobots/component/constraint/model/CableModel.h, src/SoftRobots/component/constraint/model/CableModel.inl, src/SoftRobots/component/constraint/model/SurfacePressureModel.h, src/SoftRobots/component/constraint/model/SurfacePressureModel.inl, src/SoftRobots/component/controller/AnimationEditor.cpp, src/SoftRobots/component/forcefield/PREquivalentStiffnessForceField.h, src/SoftRobots/component/forcefield/PartialRigidificationForceField.h, src/SoftRobots/component/forcefield/PipeForceField.h
Follow lifecycle of SOFA
Needs the previous PR #91 for the github actions to be green
=> Fix for compilation v21.12

src/SoftRobots/component/camera/PointCloudProcessing.h, src/SoftRobots/component/camera/PointCloudStreaming.h, src/SoftRobots/component/forcefield/PREquivalentStiffnessForceField.h
vector.h moved: sofa/helper/vector.h -> sofa/type/vector.h
=> Fix compilation with SOFA v21.12

.github/workflows/ci.yml
The ci.yml is now more focused on continuous integration and is no more in charge of releases.
=> [SofaRobots] Remove the deploy phase in the ci.yml

docs/sofapython3/tutorials/CableGripper/myproject/finger.py
`myproject/finger.py` was still using the old `stlib.scene` module instead of `stlib3.scene` as in `details/finger.py`
=> [tutorials] FIX CableGripper with python3

src/SoftRobots/component/controller/AnimationEditor.h, src/SoftRobots/component/controller/DataVariationLimiter.h, src/SoftRobots/component/controller/SerialPortBridgeGeneric.h, src/SoftRobots/component/forcefield/PREquivalentStiffnessForceField.h, src/SoftRobots/component/forcefield/PREquivalentStiffnessForceField.inl, src/SoftRobots/component/forcefield/PartialRigidificationForceField.h, src/SoftRobots/component/forcefield/PartialRigidificationForceField.inl, src/SoftRobots/component/forcefield/PipeForceField.h, src/SoftRobots/component/forcefield/PipeForceField.inl, tests/component/constraint/SurfacePressureConstraintTest.cpp, tests/component/constraint/UnilateralPlaneConstraintTest.cpp, tests/component/controller/AnimationEditorTest.cpp, tests/component/controller/DataVariationLimiterTest.cpp, tests/component/controller/SerialPortBridgeGenericTest.cpp, tests/component/engine/VolumeFromTetrahedronsTest.cpp, tests/component/engine/VolumeFromTrianglesTest.cpp
=> Follow SOFA last changes

docs/sofapython3/examples/component/controller/CommunicationController/__init__.py, docs/sofapython3/tutorials/CableGripper/myproject/finger.py, docs/sofapython3/tutorials/PneunetGripper/details/step7-grabTheCube.py, docs/sofapython3/tutorials/PneunetGripper/pneunetgripper-tuto.md, src/SoftRobots/component/controller/AnimationEditor.h, src/SoftRobots/component/controller/DataVariationLimiter.h, src/SoftRobots/component/controller/SerialPortBridgeGeneric.h, src/SoftRobots/component/forcefield/PREquivalentStiffnessForceField.h, src/SoftRobots/component/forcefield/PREquivalentStiffnessForceField.inl, src/SoftRobots/component/forcefield/PartialRigidificationForceField.h, src/SoftRobots/component/forcefield/PartialRigidificationForceField.inl, src/SoftRobots/component/forcefield/PipeForceField.h, src/SoftRobots/component/forcefield/PipeForceField.inl, tests/component/constraint/SurfacePressureConstraintTest.cpp, tests/component/constraint/UnilateralPlaneConstraintTest.cpp, tests/component/controller/AnimationEditorTest.cpp, tests/component/controller/DataVariationLimiterTest.cpp, tests/component/controller/SerialPortBridgeGenericTest.cpp, tests/component/engine/VolumeFromTetrahedronsTest.cpp, tests/component/engine/VolumeFromTrianglesTest.cpp
Simple update of v22.06 branch to get all NG errors fixed.
=> Update v22.06 branch

src/SoftRobots/component/behavior/SoftRobotsBaseConstraint.cpp, src/SoftRobots/component/behavior/SoftRobotsBaseConstraint.h, src/SoftRobots/component/behavior/SoftRobotsConstraint.cpp, src/SoftRobots/component/behavior/SoftRobotsConstraint.h, src/SoftRobots/component/behavior/SoftRobotsConstraint.inl, src/SoftRobots/component/constraint/CableConstraint.cpp, src/SoftRobots/component/constraint/CableConstraint.h, src/SoftRobots/component/constraint/CableConstraint.inl, src/SoftRobots/component/constraint/PartialRigidificationConstraint.cpp, src/SoftRobots/component/constraint/PartialRigidificationConstraint.h, src/SoftRobots/component/constraint/PartialRigidificationConstraint.inl, src/SoftRobots/component/constraint/SurfacePressureConstraint.cpp, src/SoftRobots/component/constraint/SurfacePressureConstraint.h, src/SoftRobots/component/constraint/SurfacePressureConstraint.inl, src/SoftRobots/component/constraint/UnilateralPlaneConstraint.cpp, src/SoftRobots/component/constraint/UnilateralPlaneConstraint.h, src/SoftRobots/component/constraint/UnilateralPlaneConstraint.inl, src/SoftRobots/component/initSoftRobots.cpp, src/SoftRobots/component/initSoftRobots.h.in
Mainly:
- clean some template instantiations
- concatenate namespace
- convert from double to SReal or from double to Real
- Make methods const
=> A session of cleaning

src/SoftRobots/component/constraint/PositionConstraint.cpp, src/SoftRobots/component/constraint/model/CableModel.cpp, src/SoftRobots/component/constraint/model/PositionModel.cpp, src/SoftRobots/component/constraint/model/SurfacePressureModel.cpp, src/SoftRobots/component/controller/AnimationEditor.cpp, src/SoftRobots/component/controller/DataVariationLimiter.cpp, src/SoftRobots/component/engine/CenterOfMass.cpp, src/SoftRobots/component/engine/VolumeFromTetrahedrons.cpp, src/SoftRobots/component/engine/VolumeFromTriangles.cpp, src/SoftRobots/component/forcefield/PREquivalentStiffnessForceField.cpp, src/SoftRobots/component/forcefield/PREquivalentStiffnessForceField.h, src/SoftRobots/component/forcefield/PartialRigidificationForceField.cpp, src/SoftRobots/component/forcefield/PartialRigidificationForceField.h, src/SoftRobots/component/forcefield/PipeForceField.cpp, src/SoftRobots/component/forcefield/PipeForceField.h
The one on PositionModel prevented the compilation of SoftRobots.Inverse on Windows
=> Add missing _API attribute

examples/component/constraint/SurfacePressureConstraint/SurfacePressureConstraint.py
Because this scene timeouts regularly on the SOFA CI, I made some optimizations
Before:
100 iterations done in 7.06994 s ( 14.1444 FPS)
After:
100 iterations done in 4.05716 s ( 24.6478 FPS)
=> Speedup SurfacePressureConstraint.py

examples/tutorials/CableGripper/details/step0.py, examples/tutorials/CableGripper/details/step6.py, examples/tutorials/FirstSteps/details/step1.py, examples/tutorials/FirstSteps/details/step3.py, examples/tutorials/FirstSteps/details/step4.py, examples/tutorials/PneunetGripper/details/step7-grabTheCube.py, examples/tutorials/PneunetGripper/details/step7-withSTLIB.py, examples/tutorials/Tripod/details/maze.py, examples/tutorials/Tripod/details/step6.py, examples/tutorials/Tripod/myproject/maze.py, examples/tutorials/Tripod/myproject/parts/maze.py, examples/tutorials/Tripod/myproject/step6.py
For compatibility with: https://github.com/sofa-framework/sofa/pull/4205
=> [examples] Update all scenes not providing compliance info

examples/thematicalDocs/T1-Elements_TetraHexaBeam/Hexa/Hexa.py
There is a discrepancy between the topology and the state container. For this reason, the BoxROI crashed
=> Fix crash in scene

extensions/CUDA/src/SoftRobots/CUDA/init.cpp
Based on https://github.com/SofaDefrost/SoftRobots/pull/259 and requires https://github.com/sofa-framework/sofa/pull/4453. Only the last commit is important.
=> Initialize SofaCUDA

tests/CMakeLists.txt, tests/component/constraint/SurfacePressureConstraintTest.cpp
Following https://github.com/sofa-framework/sofa/pull/4495
=> Fix simple api since SOFA changes

.github/workflows/ci.yml
This might not work in the first try, let's see if the actions are happy.
=> [CI] update builder and script version

examples/tutorials/Tripod/details/step1.py, examples/tutorials/Tripod/myproject/step1.py
With PR https://github.com/sofa-framework/sofa/pull/3927 a mass should be defined by default
This applies the change in the example scene defining a UniformMass without any mass input
=> [examples] step1.py define a mass value

src/SoftRobots/component/controller/AnimationEditor.cpp
initSoftRobots.h must be included before ObjectFactory.h
=> Fix module name for AnimationEditor

tests/component/constraint/scenes/SurfacePressureConstraint.scn
and add the required `RequiredPlugin` for it
=> Replace FreeMotionMasterSolver (alias) with FreeMotionAnimationLoop (original name)

examples/thematicalDocs/T4-DirectActuation/Actuators/Pneumatic/SurfaceConstraintPressure.py, python3/softrobots/inverse/actuators/pneumatic.py, python3/softrobots/inverse/effectors/volumeEffector.py, python3/softrobots/sensors/pneumaticSensor.py
MeshObjLoader is an alias which is being phased out.
=> Use MeshOBJLoader instead of MeshObjLoader

tests/component/constraint/scenes/SurfacePressureConstraint.scn
This one was forgotten in #301
=>  Use MeshOBJLoader instead of MeshObjLoader (again)

src/SoftRobots/component/constraint/model/SurfacePressureModel.inl, src/SoftRobots/component/controller/AnimationEditor.cpp, src/SoftRobots/component/controller/AnimationEditor.inl, src/SoftRobots/component/forcefield/PREquivalentStiffnessForceField.inl, src/SoftRobots/component/forcefield/PartialRigidificationForceField.inl, src/SoftRobots/component/forcefield/PipeForceField.inl, tests/component/constraint/UnilateralPlaneConstraintTest.cpp, tests/component/controller/AnimationEditorTest.cpp, tests/component/controller/DataVariationLimiterTest.cpp, tests/component/controller/SerialPortBridgeGenericTest.cpp, tests/component/engine/VolumeFromTetrahedronsTest.cpp, tests/component/engine/VolumeFromTrianglesTest.cpp
To fix compilation related to https://github.com/sofa-framework/sofa/pull/5245/
=> Fix compilation further to Lifecycle v25.06

src/SoftRobots/component/behavior/SoftRobotsBaseConstraint.h, src/SoftRobots/component/behavior/SoftRobotsConstraint.inl
Rename after https://github.com/sofa-framework/sofa/pull/5423. Don't merge until this PR is merged
=> Sofa class baseconstraint

extensions/CUDA/CMakeLists.txt, extensions/CUDA/src/SoftRobots/CUDA/component/forcefield/CUDAPREquivalentStiffnessForceField.cpp, extensions/CUDA/src/SoftRobots/CUDA/component/forcefield/CUDAPartialRigidificationForceField.cpp, extensions/CUDA/src/SoftRobots/CUDA/component/forcefield/CUDAPipeForceField.cpp
Referring to https://github.com/sofa-framework/sofa/pull/5480
=> Make it compatible with SofaCUDA refresh

.github/workflows/ci.yml
[SoftRobots.Inverse CI fails](https://sofa-framework.org:5000/dashboard) due to missing binary zip files from SoftRobots.
The upload seems to fail due to some GitHub failure
This seems to be a way to fix it (not sure!)
=> [Action] Add sleep to hopefully fix upload at release

tests/component/constraint/scenes/SurfacePressureConstraint.scn
=> Add required plugin to instanciate VolumeFromTriangles component
