component/constraint/model/CableModel.h
component/constraint/model/SurfacePressureModel.h

This PR fix an issue that appear when you try to use the SOFA SoftRobots plugin with the private SOFA plugin SoftRobots.Inverse.
The problem occur particularly when you compile both on windows : 
errors appear about missing links from SoftRobots.Inverse of the SoftRobots class "SurfacePressureModel" and "CableModel.
By adding the SOFA macro "SOFA_SOFTROBOTS_API" for both class the problem should be resolved.
I also note that this macro is missing for other class of SoftRobots, is it by choice ?
Thanks in advance

[constraint] Add SOFA macro to create dll link

---

component/controller/AnimationEditor.inl

Well current SoftRobots version does not compile against recent sofa.

[SoftRobots] FIX compilation problem with #include<GL/glut.h>

---

component/constraint/CableConstraint.h
component/constraint/CableConstraint.inl
component/constraint/PartialRigidificationConstraint.inl
component/constraint/SurfacePressureConstraint.h
component/constraint/SurfacePressureConstraint.inl
component/constraint/UnilateralPlaneConstraint.h
component/constraint/UnilateralPlaneConstraint.inl
component/constraint/model/CableModel.h
component/constraint/model/CableModel.inl
component/constraint/model/SurfacePressureModel.h
component/constraint/model/SurfacePressureModel.inl
component/controller/AnimationEditor.inl
component/controller/CommunicationController.inl
component/controller/DataVariationLimiter.inl
component/controller/SerialPortBridgeGeneric.cpp
component/engine/CenterOfMass.inl
component/engine/VolumeFromTetrahedrons.inl
component/engine/VolumeFromTriangles.inl
component/forcefield/PREquivalentStiffnessForceField.h
component/forcefield/PREquivalentStiffnessForceField.inl
component/forcefield/PartialRigidificationForceField.inl
component/forcefield/PipeForceField.inl
tests/component/constraint/SurfacePressureConstraintTest.cpp

This merge request contains some general cleaning, but mostly:   
I added the use of m_componentstate to avoid segfault (as Damien did on SoftRobots.Inverse/SlidingActuator)

[component] added component state management to prevent segfault

---

docs/tutorials/Tripod/details/actuatedarm.py
docs/tutorials/Tripod/details/fixingbox.py
docs/tutorials/Tripod/details/step1.pyscn
docs/tutorials/Tripod/details/step2.pyscn
docs/tutorials/Tripod/details/step3.pyscn
docs/tutorials/Tripod/details/step6.pyscn
docs/tutorials/Tripod/details/step7.pyscn
docs/tutorials/Tripod/details/step8.pyscn
docs/tutorials/Tripod/details/tripod.py
docs/tutorials/Tripod/details/tripodcontroller.py
src/SoftRobots/component/controller/SerialPortBridgeGeneric.cpp

There were some problems with:
-fixingbox's call to getOrientedBoxFromTransform()
-setupanimation in step6 and step7
Other changes are to remove warnings.

[docs.tutorials] some fix, and cleaning to remove warnings in Tripod tutorial

---

docs/examples/component/constraint/CableConstraint/sofapython3/Finger.py3
docs/examples/component/constraint/CableConstraint/sofapython3/FingerController.py

A full tutorial scene converted from SofaPython (2) to SofaPython3.
Not much changes between the 2 APIs:
- `createObject` / `createChild` is deprecated in favor of `addChild` / `addObject`
- Controllers change slightly:
-- constructors must call parent class's ctor
-- event methods are now clearly named after their event type (`onBeginAnimationStep` becomes `onAnimateBeginEvent`) (prefix `on` is added to the return value of `Event::GetClassName()`)
-- all event method takes a dict as a parameter, containing all useful values (instead of directly feeding them as arguments to the function
-- it is not possible any more to create a controller using the `createObject` method on nodes. Instead their constructors should be called and then the instance is assigned to an `addObject` call.
- we …

first sofapython3 scene (Finger with cable constraints)

---

CMakeLists.txt

@damienmarchal I'm not a cmake expert, but there's no need to add SofaPython(3) with target_link_libraries() right?

[cmakelists] fix compile SofaPython3

---

src/SoftRobots/component/constraint/model/AffineFunctionModel.inl
src/SoftRobots/component/constraint/model/CableModel.inl
src/SoftRobots/component/constraint/model/SurfacePressureModel.inl

This PR:
- adds a warning info about the dependence between the "force" and dt in constraint components
- removes compilation warnings about `<0` always being false due to the variable type

[constraint] Warnings for the dependence between the force and dt

---

src/SoftRobots/component/behavior/SoftRobotsConstraint.inl
src/SoftRobots/component/constraint/UnilateralPlaneConstraint.h
src/SoftRobots/component/constraint/UnilateralPlaneConstraint.inl
src/SoftRobots/component/controller/AnimationEditor.inl
src/SoftRobots/component/controller/CommunicationController.inl
tests/component/constraint/SurfacePressureConstraintTest.cpp
tests/component/constraint/UnilateralPlaneConstraintTest.cpp
tests/component/controller/AnimationEditorTest.cpp
tests/component/controller/DataVariationLimiterTest.cpp
tests/component/controller/SerialPortBridgeGenericTest.cpp
tests/component/engine/VolumeFromTetrahedronsTest.cpp
tests/component/engine/VolumeFromTrianglesTest.cpp

List of fixed warnings:
- new packaging:
- linearalgebra
- statecontainer
- <0 always false
- zmq deprecated methods

[all] Fix warnings for v22.06

---

cmake/environment.cmake

When building in-tree, this line pollutes the CMAKE_INSTALL_PREFIX of SOFA.
This change should be done in all Defrost plugins.
Fixes #183

[CMake] FIX install prefix when building in-tree

---

CMakeLists.txt
docs/sofapython3/examples/component/constraint/PositionConstraint/PositionConstraint.py
src/SoftRobots/component/constraint/PositionConstraint.cpp
src/SoftRobots/component/constraint/PositionConstraint.h
src/SoftRobots/component/constraint/PositionConstraint.inl
src/SoftRobots/component/constraint/model/PositionModel.cpp
src/SoftRobots/component/constraint/model/PositionModel.h
src/SoftRobots/component/constraint/model/PositionModel.inl

This PR adds two classes:
- PositionConstraint: this component allows to impose a displacement to a set of points, using a constraint approach with Lagrange's multipliers. See example `docs/sofapython3/examples/component/constraint/PositionConstraint/PositionConstraint.py`. 
- PositionModel: shared implementation of PositionConstraint and PositionEffector (for inverse resolution).

[constraint] adds PositionConstraint with example

---

.github/workflows/ci.yml

This fixes the broken CI from #230, preventing from generating assets for the release.
This is identical to https://github.com/SofaDefrost/Cosserat/pull/82 .
If approved, this might be considered to be integrated into master as well for preventing similar issues in future releases.

Fix install SofaPython3 CI action.

---

.github/workflows/ci.yml

Source code archives (zip and tar) are generated from `master` branch instead of `v23.06`. Other assets (releases for Windows, Linux and MacOS) are generated from correct branch.

Fix source code archives assets from release branch and not master.

---

.github/workflows/ci.yml

Propagate #231 into `master`, similarly to what have been done for SofaPython3: https://github.com/sofa-framework/SofaPython3/pull/364.
This allows to create the new release even if one build have failed, which is currently the case with the macOS broken CI.
Seems desirable to keep this behavior into `master` for the future releases.

Allow creation of new release even if one build (macOS) fails.

---

.github/workflows/ci.yml

The `softprops/action-gh-release` Github action used in the CI to deploy assets was incorrectly configured to the `master` branch (default behavior), instead of the current release set by the `sofa_branch` field in the `build-and-test` matrix.
This lead to the following undesired behavior:
- source code archives (zip and tar) were generated from master branch instead of release branch. Other assets (releases for Windows, Linux and MacOS) were generated from correct branch.
- release tag pushed by this action (tag in the form `release-<version>`) was incorrectly set to `master` branch, which is invalid when current release is not `master` (such as `v<version>`)

Fix softprops/action-gh-release source from master to release branch

---

CMakeLists.txt

This PR removes plugin python2 support. This will avoid polluting etc/sofa/python.d/ path with some invalid python paths that would be then considered in the setup python environment phase of SofaPython3 plugin.

Remove python2 support

---

examples/.scene-tests

Since https://github.com/SofaDefrost/SoftRobots/pull/246

Ignore step7.py as it requires the serial module

---

examples/tutorials/CableGripper/details/step0.py
examples/tutorials/CableGripper/details/step6.py
examples/tutorials/FirstSteps/details/step1.py
examples/tutorials/FirstSteps/details/step3.py
examples/tutorials/FirstSteps/details/step4.py
examples/tutorials/PneunetGripper/details/step7-grabTheCube.py
examples/tutorials/PneunetGripper/details/step7-withSTLIB.py
examples/tutorials/Tripod/details/maze.py
examples/tutorials/Tripod/myproject/maze.py
examples/tutorials/Tripod/myproject/parts/maze.py

Further to deeper investigation in https://github.com/sofa-framework/sofa/pull/4205, the previous #247 should be reverted.
Other files were already fixed by the team :+1: 
As an explanation/reminder, in a rigid case, the `compliance` data of the UncoupledCC has 7 inputs:
- 1 corresponding to the compliance for the translational dofs
- 6 corresponding to the rotation compliance matrix where zero values are possible OUTSIDE the diagonal

Revert #247

---

src/SoftRobots/component/constraint/model/CableModel.inl

This reverts commit 6e06e88e56d8938d37e1ff0b54ea57bfd49de215.

Revert "[model] missing normalize force direction (#263)"

---

examples/.scene-tests

Jenkins CI was experiencing timeout on this scene near the end of the execution. 
--> see [log](https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/PR-4679/CI_CONFIG=ubuntu_gcc,CI_PLUGINS=options,CI_TYPE=release/22/testReport/SceneTests/applications_plugins_SoftRobots_examples_thematicalDocs_T4-DirectActuation_Actuators_Pneumatic/SurfaceConstraintPressure_py/)

Try to fix scene timeout on ubuntu

---

.github/workflows/ci.yml

SOFA binaries for macOS are now generated using macos-14 runner which uses an arm64 architecture. We have to update our macOS runner consequently here to be able to compile with the arm64 SOFA binaries under macOS.

Update macos runner to arm64 arch
